image: gitpod/workspace-full-vnc
tasks:
  - init: "sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev && sudo apt-get install -y libxi-dev && sudo apt-get install -y libxcursor-dev && sudo apt-get install -y libxinerama-dev && sudo apt-get install -y libxrandr-dev"