image: gitpod/workspace-full-vnc
tasks:
  - init: "sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev libxi-dev libxcursor-dev libxinerama-dev libxrandr-dev libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev"